routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.tampilandepan');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/* Route::get('/posts/create', 'PostController@create');
Route::post('/posts', 'PostController@store');
Route::get('/posts', 'PostController@index');
Route::get('/posts/{id}', 'PostController@show');
Route::get('/posts/{id}/edit', 'PostController@edit');
Route::put('/posts/{id}', 'PostController@update');
Route::delete('/posts/{id}', 'PostController@destroy'); */

Route::resource('posts','PostController');
Route::resource('profile', 'ProfileController');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');
Route::post('/reply/store', 'ReplyController@replyStore')->name('reply.add');
// Route::post('/komen/{bloge_id}','JawabanController@store');
Route::get('/posts/cetak_pdf', 'PostController@cetak_pdf');
Route::get('users/export/', 'UsersController@export');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $table = "profiles";
     protected $guarded =[];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function bloges(){
        return $this->hasMany('App\Post','profile_id');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profile;
use App\User;
use DB;

class ProfileController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth')->except(['index']);
    }

    public function index()
    {
        $items = Profile::all();
        return view('pages.profile.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.profile.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:profiles|max:255',
            'email' => 'required'
        ]);

        
       /*  $query = DB::table('questions')->insert([
            'judul'=>$request["judul"],
            'isi' =>$request["isi"]
        ]); */
        $item = Profile::create([
            "name"=>$request["name"],
            "email"=>$request["email"]
        ]);
        
        return redirect('/profile');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $items = Profile::find($id);
        return view('pages.profile.edit', compact('items'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required',
        ]);
        

        $update = Profile::where('id', $id)->update([
            "name" => $request["name"],
            "email" => $request["email"],
        ]);

        return redirect('/profile');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Profile::destroy($id);
        return redirect('/profile');
    }
}

resources/views/pages/profile/create.blade.php
@extends('layouts.master')

@section('content')
   <div class="ml-3 mt-3">
       <div class="card card-primary">
           <div class="card-header">
               <h3 class="card-title">Buat Profile</h3>
           </div>
           <form action="/profile" method="POST">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="name">Nama Lengkap</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', '') }}" placeholder="Masukkan nama lengkap anda">
                    @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror      
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email', '') }}" placeholder="Masukkan email">
                    @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror      
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Buat</button>
            </div>
            </form>
       </div>
   </div>
@endsection

resources/views/pages/profile/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="m-3">
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Edit Profile {{$items->id}}</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/profile/{{$items->id}}" method="POST">
    @csrf
    @method('PUT')
      <div class="card-body">
        <div class="form-group">
          <label for="name">Nama Lengkap</label>
          <input type="text" class="form-control" id="name" name="name" value="{{old ('name', $items->name)}}" placeholder="Masukkan nama lengkap">
          @error('nama_lengkap')
            <div class="alert alert-danger">Form nama harus diisi</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name="email" value="{{old ('email', $items->email)}}" placeholder="Masukkan email" readonly>
        </div>
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </form>
  </div>
</div>


@endsection

resources/views/pages/profile/index.blade.php
@extends('layouts.master')

@section('content')
<br><br><br>
<a class="btn btn-info mb-1" href="{{route('profile.create')}}">Add datadiri</a>
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{{url('assets/dist/img/user2-160x160.jpg')}}" class="card-img">
      </div>
      <div class="col-md-8">
        <div class="card-body">
         @foreach ($items as $item)
         <p class="card-text"> {{$item->name}}</p>
        <p class="card-text"> {{$item->email}}</p>
        <a href="{{route('profile.edit',['profile'=>$item->id])}}" class="btn btn-warning btn-sm">Edit</a>
        <form action="{{route('profile.destroy',['profile'=>$item->id])}}" method="post">
            @csrf
            @method('DELETE')
            <input type="submit" value="delete" class="btn btn-danger btn-sm">
          </form>
         @endforeach
        </div>
        
      </div>
    </div>
    
    
  </div>
@endsection