routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.tampilandepan');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/* Route::get('/posts/create', 'PostController@create');
Route::post('/posts', 'PostController@store');
Route::get('/posts', 'PostController@index');
Route::get('/posts/{id}', 'PostController@show');
Route::get('/posts/{id}/edit', 'PostController@edit');
Route::put('/posts/{id}', 'PostController@update');
Route::delete('/posts/{id}', 'PostController@destroy'); */

Route::resource('posts','PostController');
Route::resource('profile', 'ProfileController');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');
Route::post('/reply/store', 'ReplyController@replyStore')->name('reply.add');
// Route::post('/komen/{bloge_id}','JawabanController@store');
Route::get('/posts/cetak_pdf', 'PostController@cetak_pdf');
Route::get('users/export/', 'UsersController@export');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/includes/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
      Copyright &copy; 2020 <div class="bullet"></div> Re-Write by <a href="https://nauval.in/">Re-blog</a>
    </div>
    <div class="footer-right">

    </div>
  </footer>

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
      <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
      </ul>
    </form>
    <ul class="navbar-nav navbar-right">
        @guest
        <form>
            <button type="button" class="btn btn-primary" onclick="event.preventDefault();location.href='{{url('login')}}'">
                login
              </button>
        </form>
        @endguest
        @auth
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
          <img alt="image" src="{{url('assets/dist/img/avatar/avatar-1.png')}}" class="rounded-circle mr-1">
          <div class="d-sm-none d-lg-inline-block">Hi, {{Auth::user()->name}}</div></a>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="{{route('profile.index')}}" class="dropdown-item has-icon">
              <i class="far fa-user"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
          <form action="{{url('logout')}}" method="POST">
            @csrf
            <button class="btn btn-danger" type="submit">
              <i class="fas fa-sign-out-alt"></i> Logout
            </button>
          </form>
          </div>
        </li>
        @endauth
      </ul>
  </nav>

resources/views/includes/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="index.html">Reblog</a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="index.html">R-B</a>
      </div>
      <ul class="sidebar-menu">
        <li><a class="nav-link" href="{{url('/posts')}}  "><i class="far fa-square"></i> <span>Dashboard</span></a></li>
      </ul>
    </aside>
  </div>

resources/views/includes/top.blade.php
<div>
    <div class="top-rated">
        <h3>Top Rated</h3>
        <a href = "#">
            <div class="content">
                <h4>01</h4>
                <h5>Perhapas you have wonderem namber used samsdfa sdfas adsfa sdfa sd</h5>
            </div>
        </a>

        <a href = "#">
            <div class="content">
                <h4>02</h4>
                <h5>Perhapas you have wonderem namber used</h5>
            </div>
        </a>

        <a href = "#">
            <div class="content">
                <h4>03</h4>
                <h5>Perhapas you have wonderem namber used</h5>
            </div>
        </a>
    </div>
</div>