routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.tampilandepan');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/* Route::get('/posts/create', 'PostController@create');
Route::post('/posts', 'PostController@store');
Route::get('/posts', 'PostController@index');
Route::get('/posts/{id}', 'PostController@show');
Route::get('/posts/{id}/edit', 'PostController@edit');
Route::put('/posts/{id}', 'PostController@update');
Route::delete('/posts/{id}', 'PostController@destroy'); */

Route::resource('posts','PostController');
Route::resource('profile', 'ProfileController');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');
Route::post('/reply/store', 'ReplyController@replyStore')->name('reply.add');
// Route::post('/komen/{bloge_id}','JawabanController@store');
Route::get('/posts/cetak_pdf', 'PostController@cetak_pdf');
Route::get('users/export/', 'UsersController@export');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/pages/comment.blade.php
<div class = "komentar">
    <hr class="line-koment">
<h5 class="sumKomentar">Komentar - <span class="bilkoment">{{$post->comments->count()}}</span></h5>


  <div class="media-list">
      @foreach ($post as $item)
          <div class="media">
            <a href="#" class="mr-3 mt-3 media-left">
                <img src="{{asset('assets/artikel/img/1.jpg')}}" />
            </a>
          </div>
          <div class="media-body">
            <div class="wrap-body">
            <h1 class="media-heading"></h1>

            <div class="media-chat">
            <div class="comment-date"></div>

            <div class="btn-aksi">
                <a href="">
                    <i class=" btn-like far fa-thumbs-up"></i>
                </a>
                <a href="">
                    <i class=" btn-like far fa-thumbs-down"></i>
                </a>
                <a href="" class="btn btn-warning btn-circle text-uppercase" data-toggle="collapse" href="#collapsekomen">
                    <span class="glyphicon glyphicon-comment"></span> comments
                    <i class="fas fa-reply"></i>
                </a>
            </div>
            </div>
            </div>
            <div class="sub-koment collapse" id="collapsekomen">
                <form action="">
                    @csrf
                    <textarea class="form-control" id="content" name="content"></textarea>
                    <input style="margin-bottom: 20px;margin-top: 10px" class="btn btn-success" type="submit" name="subkomen" id="btn-koment" value="Kirim">
                </form>
            </div>
          </div>
      @endforeach
  </div>
    <div class="form-komentar">
        <form action="/komen/{{$post->id}}" method="post">
            @csrf
                    <textarea class="form-control" id="content" name="content"></textarea>
                    <input class="btn btn-success" type="submit" name="content" id="btn-content" value="Kirim">
            </form>
    </div>
</div>

resources/views/pages/create.blade.php
@extends('layouts.master')
@push('script-head')
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('content')


    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form role="form" action="/posts" method="POST">
            @csrf
          <div class="card-body">
              <h1>Write your mind...</h1>
            <div class="form-group">
              <label for="title">Title</label>
            <input type="text" class="form-control" id="title" value="{{old('title')}}" name="title" placeholder="Title">
              @error('title')
              <div class="alert alert-danger">{{ $message }}</div>
             @enderror
            </div>

            <div class="form-group">
              <label for="content">Content </label>
              <textarea name="content" class="form-control my-editor">{!! old('content', $content ?? '') !!}</textarea>

              @error('content')
              <div class="alert alert-danger">{{ $message }}</div>
          @enderror
            </div>
          </div>
            <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>

      </div>
@endsection
@push('script')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush

resources/views/pages/edit.blade.php
@extends('layouts.master')

@section('content')

<section class="content">


    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Edit Post {{$post->id}}  </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
    <form role="form" action="/posts/{{$post->id}}" method="POST">
            @csrf
            @method('PUT')
          <div class="card-body">
            <div class="form-group">
              <label for="title">Title</label>
            <input type="text" class="form-control" id="title" value="{{old('title', $post->title)}}" name="title" placeholder="Title">
              @error('title')
              <div class="alert alert-danger">{{ $message }}</div>
             @enderror
            </div>

            <div class="form-group">
              <label for="content">Content</label>
              <input type="text" class="form-control" id="content" value="{{old('content', $post->content)}}"   name="content" placeholder="content">
              @error('content')
              <div class="alert alert-danger">{{ $message }}</div>
          @enderror
            </div>
          </div>
            <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
    </section>
      </div>

@endsection

resources/views/pages/index.blade.php
@extends('layouts.master')

@section('content')
<section class="content">

    <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>
        </div>
    <div class="mt-3 ml-3">
        <div class="card">
            <div class="card-header">
              <a href="{{url('/posts/cetak_pdf')}} " class="btn btn-primary" target="_blank">Print as PDF</a>
              <a href="{{url('users/export/')}} " class="btn btn-primary" target="_blank">Download Here</a>
            <a href="{{route('posts.create')}}" class="btn btn-primary">Write Article</a>
            
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th style="width: 10px">No</th>
                    <th>Author</th>
                    <th>Judul</th>
                    <th>Isi</th>
                    <th>Di Buat Tanggal</th>
                    <th>Update</th>
                    <th style="width: 40px">Action</th>
                  </tr>
                </thead>
                <tbody>
    @foreach ($posts as $post)
        <tr>
            <th scope="row"> {{ $loop->iteration }}</th>
            {{-- <td>  {{ $post -> author -> name }} </td> --}}
            <td> {{ $post ->author->name }} </td>
            <td>  {{ $post -> title }} </td>
            <td>  {!! $post -> content !!} </td>
            <td>  {{ $post -> created_at  }} </td>
            <td>  {{ $post -> updated_at  }} </td>
        <td style="display: flex">
          <a href="{{route('posts.show',['post'=>$post->id])}}" class="btn btn-info btn-sm">Show</a>
          <a href="{{route('posts.edit',['post'=>$post->id])}}" class="btn btn-warning btn-sm">Edit</a>
          <form action="{{route('posts.destroy',['post'=>$post->id])}}" method="post">
              @csrf
              @method('DELETE')
              <input type="submit" value="delete" class="btn btn-danger btn-sm">
            </form>
        </td>
        </tr>
    @endforeach
                </tbody>
              </table>
            </div>
        </div>

    </div>
    </div>
    </div>


@endsection

resources/views/pages/show.blade.php
@extends('layouts.master')

@section('content')
<br><br>
    <div class="row artikel">
        <div class="col-md-9 col-sm-12">
            <div class="contentArtikel">
            <h1>{{$post->title}}</h1>
{{--                <figure>--}}
{{--                    <img src="{{asset('artikel/img/1.jpg')}}">--}}
{{--                    <figcaption>Medan 12 january 2020</figcaption>--}}
{{--                </figure>--}}

                <p class="diperbaharui">Diperbaharui : {{$post->updated_at}}</p>

                <div class="teks-artikel">

                   {!!$post->content!!}

{{--                <p>Ultrices natoque mus mattis, aliquam, cras in pellentesque--}}
{{--                    tincidunt elit purus lectus, vel ut aliquet, elementum nunc--}}
{{--                    nunc rhoncus placerat urna! Sit est sed! Ut penatibus turpis--}}
{{--                    mus tincidunt! Dapibus sed aenean, magna sagittis, lorem velit</p>--}}

                </div>

                <div class = "share">
                    <div class="linkshare">
                        <a href="#"><div class="twit"></div></a>
                        <a href="#"><div class="fb"></div></a>
                        <a href="#"><div class="gplus"></div></a>
                    </div>
                </div>

            </div>
        </div>
        <aside class="col-md-3 col-sm-12">
            @include('includes.top')
        </aside>
    </div>
    <h4>Display Comments</h4>
    <div class="col-md-9 col-sm-12">
    <div class="contentArtikel">
                    @include('partials._comment_replies', ['comments' => $post->comments])
                   
                </div>
    </div>
    <h4>Add comment</h4>
    <div class="col-md-9 col-sm-12">
        <div class="contentArtikel">
                    <form method="post" action="{{ route('comment.add') }}">
                        @csrf

                        <div class="form-group">
                            <input type="text" name="comment_body" class="form-control" />
                            <input type="hidden" name="post_id" value="{{ $post->id }}" />
                        </div>
                        {{-- @error('content')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror --}}
                        <div class="form-group">
                            <input type="submit" class="btn btn-warning" value="Add Comment" />
                        </div>
                    </form>
                </div>
            </div>
    {{-- @include('pages.comment') --}}
    {{-- @include('pages.comment')} --}}

@endsection


@push('style')
    <link rel="stylesheet" href="{{asset('assets/artikel/style2.css')}}">
    <link rel="stylesheet" href="{{asset('assets/artikel/comment.css')}}">
@endpush

resources/views/pages/tampilandepan.blade.php
@extends('layouts.master')

@section('content')
<section class="content">
    <br>
    <div class="container-fluid">
        <div class="section-title">
            <h2>List</h2>
        </div>
        <div class="container">
            <ul class="playlist-filter controls">
                <li class="control" data-filter="all">All Item</li>
                <li class="control" data-filter=".genres">Bahasa pemograman</li>
                <li class="control" data-filter=".artists">Komputer</li>
                <li class="control" data-filter=".movies">News</li>

            </ul>
        </div>
        <div class="clearfix"></div>
        <div style= "margin-top : -50px;" class="row playlist-area">
            <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                @if(isset($id))
                    <a style="text-decoration: none" href = "/posts/">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/laravel.png')}}" alt="">
                            <h5>Laravel</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "/posts/">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/laravel.png')}}" alt="">
                            <h5>Laravel</h5>
                        </div>
                    </a>
                @endif
            </div>

            <div class="mix col-lg-3 col-md-4 col-sm-6 movies">
                @if(isset($id))
                    <a style="text-decoration: none" href = "{{url('data-artikel/1/'.$id)}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/coding.png')}}" alt="">
                            <h5>Tentang TI</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "{{url('data-artikel/1')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/coding.png')}}" alt="">
                            <h5>Tentang TI</h5>
                        </div>
                    </a>
                @endif
            </div>

            <div class="mix col-lg-3 col-md-4 col-sm-6 movies">
                @if(isset($id))
                    <a style="text-decoration: none" href = "{{url('data-artikel/1/'.$id)}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/si.png')}}" alt="">
                            <h5>Tentang SI</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "{{url('data-artikel/1')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/si.png')}}" alt="">
                            <h5>Tentang SI</h5>
                        </div>
                    </a>
                @endif
            </div>

            <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                @if(isset($id))
                    <a style="text-decoration: none" href = "{{url('data-artikel/1/'.$id)}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/python.png')}}" alt="">
                            <h5>Python</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "{{url('data-artikel/1')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/python.png')}}" alt="">
                            <h5>Python</h5>
                        </div>
                    </a>
                @endif
            </div>

            <div class="mix col-lg-3 col-md-4 col-sm-6 artists">
                @if(isset($id))
                    <a style="text-decoration: none" href = "{{url('data-artikel/1/'.$id)}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/com.jpg')}}" alt="">
                            <h5>Tentang Komputer</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "{{url('data-artikel/1')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/com.jpg')}}" alt="">
                            <h5>Tentang Komputer</h5>
                        </div>
                    </a>
                @endif
            </div>

            <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                @if(isset($id))
                    <a style="text-decoration: none" href = "{{url('data-artikel/1/'.$id)}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/js.png')}}" alt="">
                            <h5>Javascript</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "{{url('data-artikel/1')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/js.png')}}" alt="">
                            <h5>Javacript</h5>
                        </div>
                    </a>
                @endif
            </div>

            <div class="mix col-lg-3 col-md-4 col-sm-6 genres">
                @if(isset($id))
                    <a style="text-decoration: none" href = "{{url('/data/1/')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/c.png')}}" alt="">
                            <h5>Bahasa C</h5>
                        </div>
                    </a>
                @else
                    <a style="text-decoration: none" href = "{{url('/data/1/')}}">
                        <div class="playlist-item">
                            <img src="{{asset('assets/home/img/playlist/c.png')}}" alt="">
                            <h5>Bahasa C</h5>
                        </div>
                    </a>
                @endif
            </div>

        </div>
    </div>
</section>
@endsection
@push('style')
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">
    <!-- Stylesheets -->
   {{--  <link rel="stylesheet" href="{{asset('assets/home/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/home/css/font-awesome.min.css')}}"/> --}}
    <link rel="stylesheet" href="{{asset('assets/home/css/owl.carousel.min.css')}}"/>
        <link rel="stylesheet" href="{{asset('assets/home/css/slicknav.min.css')}}"/>
    <!-- Main Stylesheets -->
    <link rel="stylesheet" href="{{asset('assets/home/css/style.css')}}"/>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
@endpush

@push('script')
    <script src="{{asset('assets/home/js/mixitup.min.js')}}"></script>
    <script src="{{asset('assets/home/js/main.js')}}"></script>
@endpush